"""Contenuti delle pagine per settore di Rispondoio.

Ogni voce genera la pagina per/<slug>/ tramite strumenti/genera_pagine.py.
Per aggiungere un settore: copia una voce, cambia i testi, rilancia lo script.

Regola: le pagine promettono solo ciò che il prodotto fa già (risponde 24/7,
capisce la richiesta, distingue clienti/fornitori/urgenze, prenota in agenda,
manda email). Niente integrazioni, SMS o funzioni non verificate.
"""

# Valori del calcolatore: perse = chiamate senza risposta a settimana,
# conv = % che diventerebbero clienti, valore = € medio di un cliente nuovo.
# Sono valori di esempio: il visitatore li cambia con i suoi.

SETTORI = [
    {
        "slug": "parrucchieri",
        "nome": "Parrucchieri e barbieri",
        "chi": "parrucchieri e barbieri",
        "form": "Parrucchieri e barbieri",
        "icona": '<circle cx="6" cy="6" r="3"/><path d="M8.12 8.12 12 12"/><path d="M20 4 8.12 15.88"/><circle cx="6" cy="18" r="3"/><path d="M14.8 14.8 20 20"/>',
        "titolo": "Segreteria telefonica AI per parrucchieri e barbieri",
        "h1": "Le mani nei capelli, il telefono che squilla.",
        "lead": "Mentre tagli, fai un colore o una piega, Rispondoio risponde al posto tuo, trova l'orario libero e scrive l'appuntamento in agenda. Tu non ti fermi, il cliente non chiama il salone accanto.",
        "descrizione": "Rispondoio risponde al telefono del tuo salone 24 ore su 24, prenota tagli, colori e pieghe in agenda e ti avvisa via email. Configurato su misura per parrucchieri e barbieri.",
        "problemi": [
            ("Interrompi il lavoro", "Ogni volta che rispondi con le mani occupate il cliente in poltrona aspetta, e il lavoro si allunga."),
            ("Chiamate dopo la chiusura", "Molti prenotano la sera o nel giorno di chiusura: se il telefono squilla a vuoto, provano altrove."),
            ("Agenda a pezzi", "Appuntamenti presi al volo su un foglio o a memoria: doppie prenotazioni e buchi in agenda."),
        ],
        "dialogo": [
            ("c", "Buongiorno, vorrei prenotare taglio e piega per sabato mattina."),
            ("r", "Certo! Sabato ho libero alle 9:30 o alle 11:00. Quale preferisce?"),
            ("c", "Le 11 vanno bene."),
            ("r", "Perfetto, sabato alle 11:00 taglio e piega. Mi lascia nome e numero?"),
            ("c", "Giulia Bianchi, 333 1234567."),
            ("r", "Fatto, Giulia: l'appuntamento è in agenda. A sabato!"),
        ],
        "fa": [
            "Prenota taglio, colore, piega e trattamenti negli orari liberi",
            "Risponde su orari, servizi e prezzi che ci indichi",
            "Prende nota di spostamenti e disdette e ti avvisa",
            "Ti manda un'email per ogni nuovo appuntamento",
        ],
        "roi": (15, 50, 35),
        "faq": [
            ("E se un cliente vuole parlare proprio con me?", "Rispondoio prende nome, numero e motivo della chiamata e ti avvisa via email: richiami tu quando hai finito con il cliente in poltrona."),
        ],
    },
    {
        "slug": "centri-estetici",
        "nome": "Centri estetici e nail bar",
        "chi": "centri estetici e nail bar",
        "form": "Centri estetici",
        "icona": '<path d="M12 2a5 5 0 0 1 5 5c0 3-2 4-2 7H9c0-3-2-4-2-7a5 5 0 0 1 5-5Z"/><path d="M9 21h6"/>',
        "titolo": "Segreteria telefonica AI per centri estetici",
        "h1": "Il trattamento non si interrompe. La prenotazione arriva lo stesso.",
        "lead": "Durante una pulizia viso o una ceretta non puoi rispondere. Rispondoio sì: risponde a ogni chiamata, spiega i trattamenti e fissa l'appuntamento nell'orario libero.",
        "descrizione": "Rispondoio risponde al telefono del tuo centro estetico 24 ore su 24, spiega i trattamenti e prenota in agenda durante la chiamata. Configurato su misura per te.",
        "problemi": [
            ("In cabina, telefono fuori", "Mentre sei con una cliente non rispondi: chi chiama per prenotare trova solo squilli."),
            ("Sempre le stesse domande", "Prezzi, durata dei trattamenti, orari: le stesse risposte, dette dieci volte al giorno."),
            ("Prenotazioni serali perse", "Molte clienti pensano a prenotare la sera, quando il centro è chiuso."),
        ],
        "dialogo": [
            ("c", "Salve, fate la laminazione ciglia? Quanto costa?"),
            ("r", "Sì! Dura circa un'ora e costa 50 euro. Vuole prenotarla?"),
            ("c", "Sì, giovedì pomeriggio se possibile."),
            ("r", "Giovedì ho libero alle 15:00 o alle 17:30. Quale preferisce?"),
            ("c", "Alle 17:30. Sono Chiara Moretti, 340 2468135."),
            ("r", "Perfetto Chiara: laminazione ciglia giovedì alle 17:30. È in agenda!"),
        ],
        "fa": [
            "Prenota trattamenti viso, corpo, unghie e depilazione",
            "Spiega trattamenti, durata e prezzi come li descrivi tu",
            "Prende nota di richieste particolari e ti avvisa",
            "Ti manda un'email per ogni nuovo appuntamento",
        ],
        "roi": (12, 50, 50),
        "faq": [
            ("Può consigliare un trattamento?", "Risponde con le informazioni che ci dai tu: trattamenti, durata, prezzi. Per una consulenza personalizzata prende i recapiti della cliente e ti avvisa."),
        ],
    },
    {
        "slug": "dentisti",
        "nome": "Studi dentistici",
        "chi": "studi dentistici",
        "form": "Studi dentistici",
        "icona": '<path d="M7 3c-2.5 0-4 2-4 4.5 0 2 1 3.5 1.5 5.5.6 2.6 1 8 3 8 1.6 0 1.6-5 4.5-5s2.9 5 4.5 5c2 0 2.4-5.4 3-8 .5-2 1.5-3.5 1.5-5.5C21 5 19.5 3 17 3c-2 0-3 1-5 1S9 3 7 3Z"/>',
        "titolo": "Segreteria telefonica AI per studi dentistici",
        "h1": "Mentre sei alla poltrona, lo studio risponde.",
        "lead": "Rispondoio risponde ai pazienti 24 ore su 24, fissa prime visite e sedute di igiene nei posti liberi e segnala subito le urgenze. La segreteria si concentra su chi è in sala d'attesa.",
        "descrizione": "Rispondoio risponde al telefono del tuo studio dentistico 24 ore su 24, prenota prime visite e igiene in agenda e segnala subito le urgenze. Configurato su misura.",
        "problemi": [
            ("Segreteria sovraccarica", "Telefono, accettazione, pagamenti: chi sta al banco non riesce a rispondere a tutto."),
            ("Prime visite perse", "Un paziente nuovo che non trova risposta chiama lo studio successivo su Google."),
            ("Urgenze fuori orario", "Il mal di denti non guarda l'orario: chi chiama la sera vuole almeno sapere che verrà richiamato."),
        ],
        "dialogo": [
            ("c", "Buonasera, ho un forte mal di denti da ieri. Potete visitarmi?"),
            ("r", "Mi dispiace. Segnalo subito la richiesta come urgente allo studio. Domattina c'è un posto alle 9:15: lo prenoto?"),
            ("c", "Sì, grazie."),
            ("r", "Fatto. Mi lascia nome e numero di telefono?"),
            ("c", "Marco Rossi, 347 7654321."),
            ("r", "Grazie Marco: appuntamento domani alle 9:15. Lo studio ha già ricevuto la sua segnalazione."),
        ],
        "fa": [
            "Prenota prime visite, igiene e controlli negli orari liberi",
            "Riconosce le urgenze e avvisa subito lo studio",
            "Dà informazioni su orari, sede e prestazioni",
            "Non dà indicazioni cliniche: raccoglie la richiesta e la passa allo studio",
        ],
        "roi": (10, 40, 150),
        "faq": [
            ("Dà consigli medici ai pazienti?", "No. È configurato per prendere appuntamenti e raccogliere richieste. Se un paziente descrive un'urgenza, lo studio riceve subito una notifica."),
        ],
    },
    {
        "slug": "studi-medici",
        "nome": "Studi medici e poliambulatori",
        "chi": "studi medici e poliambulatori",
        "form": "Studi medici e poliambulatori",
        "icona": '<path d="M11 2v2"/><path d="M5 2v2"/><path d="M5 3H4a2 2 0 0 0-2 2v4a6 6 0 0 0 12 0V5a2 2 0 0 0-2-2h-1"/><path d="M8 15a6 6 0 0 0 12 0v-3"/><circle cx="20" cy="10" r="2"/>',
        "titolo": "Segreteria telefonica AI per studi medici e poliambulatori",
        "h1": "Il telefono non è più il collo di bottiglia.",
        "lead": "Nei poliambulatori il telefono è sempre occupato. Rispondoio risponde subito, senza attesa in linea, prenota visite nell'agenda dello studio e raccoglie le richieste per il personale.",
        "descrizione": "Rispondoio risponde al telefono del tuo studio medico 24 ore su 24, prenota visite in agenda e raccoglie le richieste dei pazienti. Configurato su misura.",
        "problemi": [
            ("Linee sempre occupate", "Nelle ore di punta i pazienti richiamano più volte, oppure rinunciano."),
            ("Personale al telefono, non allo sportello", "Ogni chiamata per un'informazione toglie tempo a chi accoglie i pazienti in sede."),
            ("Richieste che si perdono", "Referti, certificati, spostamenti: messaggi su post-it che nessuno ritrova."),
        ],
        "dialogo": [
            ("c", "Buongiorno, vorrei prenotare una visita cardiologica."),
            ("r", "Certo. La prima disponibilità è martedì alle 10:30, oppure giovedì alle 16:00."),
            ("c", "Martedì va bene."),
            ("r", "Perfetto. Mi indica nome, cognome e un numero di telefono?"),
            ("c", "Anna Verdi, 340 1122334."),
            ("r", "Grazie Anna: visita cardiologica martedì alle 10:30. È tutto registrato."),
        ],
        "fa": [
            "Prenota visite nell'agenda dello studio",
            "Risponde su orari, sedi e prestazioni secondo le vostre istruzioni",
            "Raccoglie richieste di referti e certificati e le inoltra via email",
            "Segnala subito le urgenze e non dà indicazioni cliniche",
        ],
        "roi": (15, 50, 90),
        "faq": [
            ("Dà consigli medici ai pazienti?", "No. È configurato per prendere appuntamenti e raccogliere richieste. Se un paziente descrive un'urgenza, lo studio riceve subito una notifica."),
        ],
    },
    {
        "slug": "fisioterapisti",
        "nome": "Fisioterapisti e osteopati",
        "chi": "fisioterapisti e osteopati",
        "form": "Fisioterapisti e osteopati",
        "icona": '<path d="M22 12h-4l-3 9L9 3l-3 9H2"/>',
        "titolo": "Segreteria telefonica AI per fisioterapisti e osteopati",
        "h1": "Le mani sono sul paziente. Al telefono pensa Rispondoio.",
        "lead": "Durante una seduta non puoi rispondere, e chi ha mal di schiena prenota dal primo che risponde. Rispondoio fissa prime valutazioni e sedute mentre lavori.",
        "descrizione": "Rispondoio risponde al telefono del tuo studio di fisioterapia o osteopatia 24 ore su 24 e prenota valutazioni e sedute in agenda. Configurato su misura.",
        "problemi": [
            ("Sedute lunghe, telefono muto", "Per tutta la seduta il telefono resta senza risposta: in una giornata piena sono decine di chiamate."),
            ("Pazienti con dolore, poca pazienza", "Chi ha un dolore acuto cerca il primo posto libero, non aspetta la richiamata."),
            ("Richiamate a fine giornata", "La sera richiami chi ha lasciato un messaggio, e metà ha già prenotato altrove."),
        ],
        "dialogo": [
            ("c", "Salve, ho un dolore alla spalla da una settimana. Avete posto per una valutazione?"),
            ("r", "Certo. Ho disponibilità mercoledì alle 18:00 o venerdì alle 8:30."),
            ("c", "Mercoledì alle 18."),
            ("r", "Perfetto. Mi lascia nome e numero di telefono?"),
            ("c", "Luca Neri, 338 9988776."),
            ("r", "Grazie Luca: prima valutazione mercoledì alle 18:00. È in agenda."),
        ],
        "fa": [
            "Prenota prime valutazioni e sedute negli orari liberi",
            "Spiega trattamenti, durata e costi come li descrivi tu",
            "Prende nota di disdette e spostamenti e ti avvisa",
            "Non dà indicazioni cliniche: raccoglie la richiesta e la passa a te",
        ],
        "roi": (10, 50, 200),
        "faq": [
            ("Dà consigli ai pazienti sul dolore?", "No. Prende appuntamenti e raccoglie le richieste; se un paziente segnala un problema urgente, ricevi subito una notifica."),
        ],
    },
    {
        "slug": "veterinari",
        "nome": "Cliniche veterinarie",
        "chi": "cliniche e ambulatori veterinari",
        "form": "Cliniche veterinarie",
        "icona": '<circle cx="11" cy="4" r="2"/><circle cx="18" cy="8" r="2"/><circle cx="20" cy="16" r="2"/><path d="M9 10a5 5 0 0 1 5 5v3.5a3.5 3.5 0 0 1-6.84 1.045Q6.52 17.48 4.46 16.84A3.5 3.5 0 0 1 5.5 10Z"/>',
        "titolo": "Segreteria telefonica AI per cliniche veterinarie",
        "h1": "Dietro ogni chiamata c'è un animale che aspetta.",
        "lead": "Rispondoio risponde ai proprietari 24 ore su 24, prenota visite e vaccini negli orari liberi e avvisa subito la clinica quando c'è un'urgenza.",
        "descrizione": "Rispondoio risponde al telefono della tua clinica veterinaria 24 ore su 24, prenota visite e vaccini in agenda e segnala subito le urgenze. Configurato su misura.",
        "problemi": [
            ("Telefono e sala visite insieme", "Con un animale sul tavolo non puoi rispondere, e la sala d'attesa è piena."),
            ("Proprietari in ansia", "Chi chiama per il proprio animale vuole una risposta subito, non una segreteria."),
            ("Urgenze mischiate alle prenotazioni", "Un vaccino e un'emergenza arrivano dallo stesso telefono: serve capire subito quale è quale."),
        ],
        "dialogo": [
            ("c", "Buongiorno, devo fare il richiamo del vaccino al mio cane."),
            ("r", "Certo! Posso proporle sabato alle 10:00 o lunedì alle 17:30."),
            ("c", "Sabato alle 10."),
            ("r", "Perfetto. Mi dice il suo nome, il nome del cane e un numero di telefono?"),
            ("c", "Sara Galli, il cane si chiama Pepe, 349 5566778."),
            ("r", "Grazie Sara: vaccino per Pepe sabato alle 10:00. È in agenda!"),
        ],
        "fa": [
            "Prenota visite, vaccini e controlli",
            "Riconosce le urgenze e avvisa subito la clinica",
            "Dà informazioni su orari, servizi e reperibilità come le indicate voi",
            "Non dà indicazioni cliniche: raccoglie la richiesta e la passa al veterinario",
        ],
        "roi": (10, 50, 80),
        "faq": [
            ("Cosa fa in caso di emergenza?", "Raccoglie i dati e avvisa subito la clinica. Se avete un numero di reperibilità, lo comunica al proprietario: è una delle istruzioni che impostiamo in configurazione."),
        ],
    },
    {
        "slug": "ristoranti",
        "nome": "Ristoranti e pizzerie",
        "chi": "ristoranti e pizzerie",
        "form": "Ristoranti e pizzerie",
        "icona": '<path d="M4 3v18M4 8h9a3 3 0 0 1 0 6H4M18 3v18"/>',
        "titolo": "Prenotazioni telefoniche con l'AI per ristoranti e pizzerie",
        "h1": "Il servizio è pieno. Le prenotazioni continuano ad arrivare.",
        "lead": "Alle 20:30 nessuno ha tempo di rispondere al telefono. Rispondoio prende le prenotazioni dei tavoli, risponde su orari e menu e ti lascia tutto scritto in agenda.",
        "descrizione": "Rispondoio risponde al telefono del tuo ristorante 24 ore su 24, prende le prenotazioni dei tavoli e risponde su orari e menu. Configurato su misura per te.",
        "problemi": [
            ("Telefono durante il servizio", "Chi è in sala non può lasciare i tavoli per rispondere: la chiamata va persa, e il tavolo con lei."),
            ("Prenotazioni a locale chiuso", "Molti prenotano al mattino o nel giorno di chiusura, quando non c'è nessuno a rispondere."),
            ("Sempre le stesse domande", "Siete aperti? Avete piatti senza glutine? C'è parcheggio? Domande giuste, ma tolgono tempo."),
        ],
        "dialogo": [
            ("c", "Buonasera, vorrei prenotare un tavolo per quattro sabato sera."),
            ("r", "Con piacere! Sabato ho disponibilità alle 20:00 o alle 21:30."),
            ("c", "Alle 20, grazie."),
            ("r", "Perfetto. A che nome prenoto, e mi lascia un numero?"),
            ("c", "Rossi, 335 2233445."),
            ("r", "Tavolo per quattro, sabato alle 20:00, a nome Rossi. Vi aspettiamo!"),
        ],
        "fa": [
            "Prende prenotazioni con numero di persone e orario",
            "Risponde su orari, chiusure, menu e opzioni senza glutine come le indichi",
            "Prende nota di richieste per eventi e gruppi e ti avvisa",
            "Ti manda un'email per ogni nuova prenotazione",
        ],
        "roi": (20, 60, 70),
        "faq": [
            ("E se uso già un sistema di prenotazione online?", "Rispondoio scrive le prenotazioni nel calendario che colleghiamo in configurazione. Se usi un altro gestionale, ne parliamo insieme prima di partire."),
        ],
    },
    {
        "slug": "autofficine",
        "nome": "Autofficine e gommisti",
        "chi": "autofficine, carrozzerie e gommisti",
        "form": "Autofficine e gommisti",
        "icona": '<path d="M5 17h14M6 17l1.5-5h9L18 17M7 12l1-4h8l1 4"/><circle cx="7.5" cy="19" r="1.5"/><circle cx="16.5" cy="19" r="1.5"/>',
        "titolo": "Segreteria telefonica AI per autofficine e gommisti",
        "h1": "Sotto la macchina non si risponde al telefono.",
        "lead": "Con le mani sporche d'olio il telefono resta a squillare. Rispondoio prende gli appuntamenti per tagliandi, gomme e revisioni e ti scrive cosa serve a ogni cliente.",
        "descrizione": "Rispondoio risponde al telefono della tua officina 24 ore su 24, prenota tagliandi, cambi gomme e revisioni in agenda e raccoglie modello e targa. Configurato su misura.",
        "problemi": [
            ("Mani occupate, telefono che squilla", "Ogni volta che ti fermi per rispondere perdi il ritmo del lavoro in corso."),
            ("Picchi di stagione", "Cambio gomme e revisioni concentrano le chiamate in poche settimane."),
            ("Clienti che non richiamano", "Chi trova occupato cerca un'altra officina: un tagliando perso è spesso un cliente perso."),
        ],
        "dialogo": [
            ("c", "Buongiorno, devo fare il cambio gomme invernali sulla mia Panda."),
            ("r", "Certo! Ho posto giovedì alle 8:30 o venerdì alle 14:00. Le gomme sono già da voi in deposito?"),
            ("c", "No, le porto io. Giovedì alle 8:30."),
            ("r", "Perfetto. Mi lascia nome, targa e numero di telefono?"),
            ("c", "Paolo Ferri, AB123CD, 339 4455667."),
            ("r", "Fatto, Paolo: cambio gomme giovedì alle 8:30. È in agenda."),
        ],
        "fa": [
            "Prenota tagliandi, gomme, revisioni e diagnosi",
            "Raccoglie modello, targa e problema prima dell'appuntamento",
            "Risponde su orari, servizi e prezzi come li indichi",
            "Ti manda un'email per ogni nuovo appuntamento",
        ],
        "roi": (10, 40, 200),
        "faq": [
            ("Può fare un preventivo?", "Comunica i prezzi che ci indichi, per esempio un tagliando standard o il cambio gomme. Per i preventivi su misura raccoglie i dettagli e ti avvisa."),
        ],
    },
    {
        "slug": "agenzie-immobiliari",
        "nome": "Agenzie immobiliari",
        "chi": "agenzie immobiliari",
        "form": "Agenzie immobiliari",
        "icona": '<path d="M3 21V9l9-6 9 6v12M9 21v-6h6v6"/>',
        "titolo": "Segreteria telefonica AI per agenzie immobiliari",
        "h1": "Sei in visita. Il prossimo cliente sta chiamando.",
        "lead": "Gli agenti passano la giornata fuori ufficio. Rispondoio risponde a chi chiama per un annuncio, fissa le visite e ti manda ogni contatto con zona, budget e tempi.",
        "descrizione": "Rispondoio risponde al telefono della tua agenzia immobiliare 24 ore su 24, fissa le visite agli immobili e ti invia i contatti con le informazioni utili. Configurato su misura.",
        "problemi": [
            ("Agenti sempre fuori", "Tra visite e rogiti l'ufficio resta scoperto, proprio quando escono i nuovi annunci."),
            ("Chiamate sugli annunci la sera", "Chi cerca casa guarda i portali la sera e chiama subito: se non risponde nessuno, chiama l'agenzia successiva."),
            ("Contatti senza informazioni", "Un nome e un numero non bastano: per richiamare servono zona, budget e tempi."),
        ],
        "dialogo": [
            ("c", "Buonasera, chiamo per il trilocale in via Roma. È ancora disponibile?"),
            ("r", "Sì. Vuole fissare una visita? Ho posto sabato alle 10:00 o lunedì alle 18:30."),
            ("c", "Sabato alle 10."),
            ("r", "Perfetto. Cerca per acquisto o affitto, e ha un budget indicativo?"),
            ("c", "Acquisto, intorno ai 250 mila. Sono Roberto Marino, 333 9876543."),
            ("r", "Grazie Roberto: visita sabato alle 10:00. L'agente riceve subito i suoi dati."),
        ],
        "fa": [
            "Risponde alle chiamate sugli annunci",
            "Fissa le visite negli orari liberi",
            "Raccoglie zona, budget e tempi del cliente",
            "Ti invia ogni contatto via email",
        ],
        "roi": (8, 5, 3000),
        "faq": [
            ("Conosce i miei immobili?", "In configurazione inseriamo le informazioni che ci dai sugli immobili. Quando cambiano, ci scrivi e aggiorniamo l'assistente."),
        ],
    },
    {
        "slug": "idraulici-elettricisti",
        "nome": "Idraulici, elettricisti e artigiani",
        "chi": "idraulici, elettricisti e artigiani",
        "form": "Idraulici, elettricisti e artigiani",
        "icona": '<path d="M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.77-3.77a6 6 0 0 1-7.94 7.94l-6.91 6.91a2.12 2.12 0 0 1-3-3l6.91-6.91a6 6 0 0 1 7.94-7.94l-3.76 3.76z"/>',
        "titolo": "Segreteria telefonica AI per idraulici, elettricisti e artigiani",
        "h1": "Sei su un lavoro. Il prossimo cliente ti sta cercando.",
        "lead": "In cantiere o a casa di un cliente non puoi rispondere a ogni chiamata. Rispondoio prende la richiesta, capisce se è un'urgenza e fissa il sopralluogo nell'orario libero.",
        "descrizione": "Rispondoio risponde al telefono della tua ditta 24 ore su 24, distingue urgenze e preventivi e fissa sopralluoghi e interventi in agenda. Per idraulici, elettricisti e artigiani.",
        "problemi": [
            ("Al lavoro tutto il giorno", "Sotto un lavandino o su una scala non rispondi, e il cliente chiama il prossimo numero."),
            ("Urgenze e preventivi mischiati", "Una perdita d'acqua e una richiesta di preventivo arrivano allo stesso numero: serve capire subito cosa è urgente."),
            ("Messaggi che nessuno lascia", "Molti non lasciano messaggi in segreteria: vogliono parlare con qualcuno, subito."),
        ],
        "dialogo": [
            ("c", "Buongiorno, ho una perdita sotto il lavello della cucina."),
            ("r", "Capito. Segnalo la richiesta come urgente. Posso fissare un intervento oggi alle 17:00 o domani alle 8:00."),
            ("c", "Oggi alle 17, grazie."),
            ("r", "Perfetto. Mi lascia nome, indirizzo e numero di telefono?"),
            ("c", "Franca Leone, via Garibaldi 12, 347 1357924."),
            ("r", "Grazie Franca: intervento oggi alle 17:00. Il tecnico è già avvisato."),
        ],
        "fa": [
            "Distingue urgenze, interventi e preventivi",
            "Fissa sopralluoghi e interventi negli orari liberi",
            "Raccoglie indirizzo e descrizione del problema",
            "Ti avvisa via email, subito per le urgenze",
        ],
        "roi": (12, 50, 150),
        "faq": [
            ("Funziona se lavoro da solo?", "Sì, è pensato proprio per chi non può stare al telefono: tu lavori, Rispondoio prende le richieste e ti scrive cosa c'è da fare."),
        ],
    },
    {
        "slug": "palestre",
        "nome": "Palestre e personal trainer",
        "chi": "palestre, studi di pilates e personal trainer",
        "form": "Palestre e personal trainer",
        "icona": '<path d="M6 7v10M18 7v10M3 9v6M21 9v6M6 12h12"/>',
        "titolo": "Segreteria telefonica AI per palestre e personal trainer",
        "h1": "Chi chiama per iscriversi non deve trovare occupato.",
        "lead": "Rispondoio risponde alle richieste di informazioni, spiega corsi e abbonamenti e fissa la lezione di prova. Lo staff resta in sala con chi si allena.",
        "descrizione": "Rispondoio risponde al telefono della tua palestra 24 ore su 24, spiega corsi e abbonamenti e fissa le lezioni di prova in agenda. Configurato su misura.",
        "problemi": [
            ("Staff in sala, non al banco", "Durante i corsi e nelle ore di punta nessuno può rispondere al telefono."),
            ("Curiosi che non tornano", "Chi chiama per informazioni è pronto a iscriversi: se non trova risposta, l'entusiasmo passa."),
            ("Domande sempre uguali", "Orari, corsi, prezzi, parcheggio: le stesse informazioni ripetute ogni giorno."),
        ],
        "dialogo": [
            ("c", "Ciao, vorrei informazioni sui corsi di pilates."),
            ("r", "Certo! Il pilates è il martedì e il giovedì alle 19:00. Vuoi provare una lezione?"),
            ("c", "Sì, giovedì."),
            ("r", "Perfetto. Mi lasci nome e numero di telefono?"),
            ("c", "Elena Russo, 346 7788990."),
            ("r", "Fatto, Elena: lezione di prova giovedì alle 19:00. Ti aspettiamo!"),
        ],
        "fa": [
            "Spiega corsi, orari e abbonamenti come li descrivi tu",
            "Fissa lezioni di prova e colloqui",
            "Prende nota di richieste di disdetta o sospensione e ti avvisa",
            "Ti manda un'email per ogni nuovo contatto",
        ],
        "roi": (10, 30, 300),
        "faq": [
            ("Gestisce anche iscrizioni e pagamenti?", "No: fissa lezioni di prova e appuntamenti in agenda e ti manda i contatti. Iscrizioni e pagamenti restano nel tuo gestionale."),
        ],
    },
    {
        "slug": "studi-professionali",
        "nome": "Studi professionali",
        "chi": "commercialisti, avvocati e studi professionali",
        "form": "Studi professionali",
        "icona": '<rect x="4" y="7" width="16" height="14" rx="2"/><path d="M9 7V5a3 3 0 0 1 6 0v2"/>',
        "titolo": "Segreteria telefonica AI per commercialisti, avvocati e studi professionali",
        "h1": "In riunione con un cliente, senza perderne un altro.",
        "lead": "Rispondoio risponde per lo studio, distingue clienti, nuovi contatti e fornitori, fissa gli appuntamenti e ti manda un'email per ogni chiamata.",
        "descrizione": "Rispondoio risponde al telefono del tuo studio professionale 24 ore su 24, distingue clienti e fornitori e fissa appuntamenti in agenda. Per commercialisti, avvocati e consulenti.",
        "problemi": [
            ("Interruzioni continue", "Ogni telefonata durante una consulenza spezza la concentrazione, e il cliente davanti a te se ne accorge."),
            ("Nuovi clienti persi", "Chi cerca un professionista chiama due o tre studi: spesso vince chi risponde per primo."),
            ("Periodi di scadenze", "Sotto scadenza il telefono non si ferma, e le richieste urgenti si perdono tra le altre."),
        ],
        "dialogo": [
            ("c", "Buongiorno, ho appena aperto la partita IVA e cerco un commercialista."),
            ("r", "Benvenuto! Posso fissarle un primo appuntamento: mercoledì alle 11:00 o venerdì alle 15:30?"),
            ("c", "Mercoledì alle 11."),
            ("r", "Perfetto. Mi indica nome, telefono e di cosa si occupa la sua attività?"),
            ("c", "Davide Conti, 331 2244668, sono un grafico freelance."),
            ("r", "Grazie Davide: primo appuntamento mercoledì alle 11:00. Lo studio riceve subito la sua richiesta."),
        ],
        "fa": [
            "Distingue clienti, nuovi contatti e fornitori",
            "Fissa appuntamenti e primi colloqui",
            "Raccoglie il motivo della chiamata e i recapiti",
            "Ti manda un'email per ogni contatto",
        ],
        "roi": (6, 30, 800),
        "faq": [
            ("Può dare informazioni sulle pratiche?", "Dà solo le informazioni generali che ci indichi, come orari, servizi e documenti da portare. Per tutto il resto raccoglie la richiesta e la passa a te."),
        ],
    },
]

# Domande comuni a tutte le pagine (solo fatti già dichiarati in homepage).
FAQ_COMUNI = [
    ("Devo cambiare numero di telefono?", "No. Di solito si attiva l'inoltro delle chiamate dal tuo numero verso Rispondoio, per esempio quando non rispondi o fuori orario: lo impostiamo insieme in fase di configurazione."),
    ("Chi lo configura?", "Noi. Scriviamo l'assistente sulla tua attività, colleghiamo calendario ed email e te lo facciamo provare: attivi il piano solo quando ti convince."),
    ("Cosa succede se finiscono i minuti del piano?", "Puoi aggiungere minuti extra: 100 minuti a € 25 (IVA esclusa)."),
    ("C'è un vincolo?", "Il piano trimestrale ha un impegno minimo di 3 mesi. Con l'annuale (12 mesi) il canone mensile è più basso e l'attivazione è gratuita su Standard e Pro."),
]
